### ISSUE TITLE
Question: how to detemine HTML comment nodes?

### ISSUE THREAD

**Issue by tmpfs** [wooorm/remark#128]
This project looks fantastic and I think it will replace my own markdown processor [mdp](https://github.com/tmpfs/mdp).

Reading over the AST documentation at [mdast](https://github.com/wooorm/mdast) I don't see anything for HTML comments, would I need to inspect an HTML node? Or could this be built in to the AST? I am also interested in determining HTML processing instruction nodes too.

This is all with a view to DSLs written in markdown for example I define my CLI programs as markdown which are then compiled to a javascript representation (for the program) and to man pages as well as help output. An example program definition is [here](https://github.com/tmpfs/rlx/blob/master/lib/rlx.md) if you are interested.

**Comment by wooorm** [comment]
Like other markdown implementations, remark treats HTML as foreign objects. HTML is not expected to be valid / make sense.
Even though inline HTML is parsed so its inner markdown can be processed correctly (related: GH-124).

I’m not introducing HTML parsing to remark/mdast, if you’re interested in a similar system for HTML, maybe [hast](https://github.com/wooorm/hast) might help. Otherwise, I suggest using regexes to parse comments / processing instructions (they’re pretty simple)

**Comment by tmpfs** [comment]
That makes sense, I figured as much. Thanks for the prompt reply.

**Comment by wooorm** [comment]
No problem, thanks for asking the question!
