### ISSUE TITLE
Remove `position: false` code

### ISSUE THREAD

**Issue by wooorm** [wooorm/remark#146]
It just adds extra code, and could easily be done by a utility afterwards.

**Comment by eush77** [comment]
`position: false` is really useful for visualizing remark trees, incl. debugging remark and plugins (otherwise the tree gets cluttered quickly). It's not too bad to have it outside core, but still.

Have you thought about separating the extra code by other means? Perhaps by a separate AST pass after `remark.parse` or using a shared node constructor that would strip it?

**Comment by wooorm** [comment]
I agree it’s handy, sometimes, but the cases where it’s used are places where a utility could also be used, (e.g., the demo, in several tests). Only downside would be the CLI, but that could implement `position: false` in some other way, through a flag maybe?

What do you mean by the second paragraph? Invoking a utility (unist-remove-position) in `Parser#parse()`?

**Comment by eush77** [comment]
> What do you mean by the second paragraph? Invoking a utility (unist-remove-position) in `Parser#parse()`?

Something like that, yes. Since I don't know exactly what difficulties is this issue about, I can't say for sure.

I was under the impression that a flag for removing position info is common across parsers/compilers ([esprima](http://esprima.org/doc/index.html), [acorn](https://github.com/ternjs/acorn)), but it's not the case ([rework](https://github.com/reworkcss/css), [postcss](https://github.com/postcss/postcss/blob/master/docs/api.md), [coffeescript](http://coffeescript.org/documentation/docs/lexer.html), [livescript](http://livescript.net/#usage)). And also I was using `JSON.stringify` to inspect nodes, I could switch to [unist-util-inspect](https://github.com/wooorm/unist-util-inspect) instead if `position` option was removed.

> Only downside would be the CLI, but that could implement `position: false` in some other way, through a flag maybe?

Why that's the case? `remark -u unist-remove-position --ast-out` could do that. It would be strange if CLI supported `--no-position`, but API didn't. Then I would suggest to refactor the code so that this would be available in API as well.

**Comment by wooorm** [comment]
The problem arises from a function which is nice to have, but not necessary.
The problem is pertinent because the current implementation handles both cases (nodes with and without position) inline; I definitely want to get rid of this duplicate code and just remove `position`s afterwards but I’m unsure whether it should be an option in core (I’d rather not) or an external utility.

I feel the JSON object is always a bit verbose, which is good for debugging but less so for displaying (thus `unist-util-inspect`), or a separate `unist-util-inspect-json` which displays only important stuff in the tree (removing positions, maybe `undefined` values too, etc.)?

> `remark -u unist-remove-position --ast-out

That wouldn’t work as `unist-remove-position` is not an attacher, but then we’re getting into a whole different problem (`.useTransformer`? unified-plugins?) :wink:

**Comment by wooorm** [comment]
I’m not entirely sure what to do, so for now I’m just going to depend on [`unist-util-remove-position`](https://github.com/wooorm/unist-util-remove-position/) in the parser for now.
