### ISSUE TITLE
Bug: Non-empty blank lines

### ISSUE THREAD

**Issue by jayvdb** [wooorm/remark#194]
If a normal line (not inside code, or near indented paragraphs, etc) has only three spaces, or more, remark trims the line to be only two spaces.

i.e. input

```
Extra sentence. Extra sentence. Extra sentence. Next line contains three spaces.
   
Now something else.
```

output: the same with two spaces where there were three (github removes the spaces in the above)

The two spaces are unnecessary as far as I can tell, and pandoc emits zero spaces for the above, irrespective of how many spaces were in the input line.

I havent seen any reason why, in this instance, two spaces is better than three or four, or zero.
I suspect it is simply to allow for line breaks at the end of a line containing text, within a paragraph.
That isnt relevant if the line doesnt contain any text.

Maybe two is a magic number for some cross-compatibility reasons?   I couldnt see any tests which explain it, and the tests are usually pretty good at explaining edge cases.  Apologies if I missed something.

IMO remark should be emitting zero spaces if it knows that the spaces on the spaces-only-line are useless, or not modifying the input line if it isnt sure.

Related, the same issue of emitting unnecessary whitespace also occurs with tabs, and tabs mixed with spaces.  If we can settle on the expected behaviour for spaces only, I can retest and create a new issue for any similar problems involving tabs.

**Comment by wooorm** [comment]
Thanks @jayvdb for stumbling on this issue! It’s two things, one of which is a bug.

The reason three (or more) spaces are turned into two spaces, is because, for a `break` node, only two are needed. There’s no reason to keep `foo···\nbar` at three spaces. Plus, that information isn’t even stored in the *Abstract* syntax tree.

The bug here, is that a blank line isn’t seen by remark as blank if it contains spaces or tabs, whereas others do see it. Blank lines delimit paragraphs. But remark only sees empty blank lines as blank lines. Other processors (GH/CM/MI) don’t.

Thanks, I’ll have a fix the coming days!
