### ISSUE TITLE
Bug: Carriage return causes infinite loop

### ISSUE THREAD

**Issue by kiwiroy** [wooorm/remark#195]
See [gist](https://gist.github.com/kiwiroy/5688b7ca29bf226c19b22c675b112d1f) for example.

```bash
npm install
npm test
```

*README.md* and *example-good.md* should be fine, *example-bad.md* is **bad**

Removing either `.remarkrc` or `example-bad.md` allows the test to pass. As does an in-place edit with perl.

```bash
perl -i -lne 's/\r//g; print' example-bad.md
```

**Comment by wooorm** [comment]
So, there’s two parts to this issue:

1. remark-lint enters infinite loop; I’ll push a fix for this;
2. Carriage returns are not supported. Fix being to strip them before passing to remark (most editors do that by default or are configurable to do it). Long term fix is to allow carriage returns everywhere where newlines are also possible in the [parser](https://github.com/wooorm/remark/blob/master/packages/remark-parse/lib/parser.js), instead of removing them in a preprocessing step. The latter will be a lot of work and I’m not really interested in doing that. But if you’d like to take a stab, I’d gladly merge a PR!

**Comment by wooorm** [comment]
I’ll use this issue to refer to the first, if you’re interested in the second, could you open a new issue?
