### ISSUE TITLE
Possible bug with standalone square bracketing

### ISSUE THREAD

**Issue by yaycmyk** [wooorm/remark#209]
I was testing out my markdown-to-jsx compiler on the markdown source of the Daring Fireball syntax website and found that remark treats `[square brackets]` as a shortcut linkReference, even though it doesn't have parens or another set of square brackets directly afterward, like:

```
[square brackets][] or [square brackets]()
```

Note that there is no link definition further in the document like:

```
[square brackets]: xyz
```

Based on the [original "spec"](https://daringfireball.net/projects/markdown/syntax#link), I don't think this is intended behavior. Thoughts?

**Comment by wooorm** [comment]
#### Background

The references don’t need extra square brackets in most markdown flavours (including the original):

```markdown
[foo]

[foo]: https://example.com
```

...works perfectly fine:

```html
<p><a href="https://example.com">foo</a></p>
```

There’s [three types](https://github.com/wooorm/mdast#linkreference) of references:  `shortcut` (`[foo]`), `collapsed` (`[foo][]`), and `full` (`[foo][foo]`). The latter two always render a link, but the first renders a link if a definition is found.

#### remark

This difference in behaviour is something that I think should be handled in the stringifier (and currently is), for example because there could be plugins inserting definitions for references without them:

```markdown
Please raise issues for [this project][package.repository] on [issues][package.bugs]
```

->

```markdown
Please raise issues for [this project][package.repository] on [issues][package.bugs]

[package.repository]: https://github.com/foo/bar
[package.bugs]: https://github.com/foo/bar/issues
```

...or a plugin could remove definitions for some reason.

##### Conclusion

And that’s why I concluded that the only way to do this properly is to have the shortcut references in the tree, have remark-lint warn for them, and determine upon stringification whether it should be text or link

---

Those are my thoughts, what are yours re this background info?

**Comment by yaycmyk** [comment]
Hmm, thanks for that background info. My inclination is toward not marking the node as a linkReference shortcut unless there's an annotation further in the document. Principle of least surprise. 

In my compiler I actually do an initial AST traversal to pluck out linkRef and imageRef definitions, then on the transpile run I match up the reference to the definition and form the appropriate JSX. It was surprising to me to receive a linkReference without accompanying definition.

**Comment by wooorm** [comment]
Yup, it’s surprising. Shortcut references are inherently surprising. And markdown is as well.

You are proposing sometimes classifying `[foo]` as reference and sometimes as text, right?
That sounds simple but it produces unstable trees. Take for example an autoformatter, where you save between adding the reference and the definition. Now the reference is escaped, and the definition is unreferenced. Or the posed plugin above (auto-insertion).

> Principle of least surprise.

Least surprise for compiling to HTML. Changing this comes with surprising results in the rest of the process.

> In my compiler I actually do an initial AST traversal to pluck out linkRef and imageRef definitions, then on the transpile run I match up the reference to the definition and form the appropriate JSX. It was surprising to me to receive a linkReference without accompanying definition.

Having a reference without definition in markdown is valid. And there’s use cases for it, albeit surprising use cases.
Take variable definitions in JavaScript without them being used. Perfectly OK as well.
Keeping up with this analogy, it’s fine, and IMO the only way, to remove them in the minifier / treat them as text in the HTML compiler.

**Comment by wooorm** [comment]
Closing. I believe this is the only way to do the AST properly, as mentioned above. If someone has another proposal I’d love to hear about it.
