### ISSUE TITLE
remark does not recognize Hugo shortcodes

### ISSUE THREAD

**Issue by dechamps** [wooorm/remark#253]
Currently, remark does not recognize [Hugo shortcodes][] - it assumes they're just plain Markdown text. This leads to problems like:

```
$ echo '{{< ref "[" >}}' | remark
{{&lt; ref "\[" >}
```

Here's a more practical example of how it's causing real problems with the workflow I'm trying to set up:

```
$ echo '{{% ref "foobar.md" %}}' | remark --use 'textr=plugins:["typographic-base"]'
{{% ref “foobar.md” %}}
```

Note the quotes. The resulting shortcode is of course broken and won't be properly parsed by Hugo.

[hugo shortcodes]: https://gohugo.io/extras/shortcodes/

**Comment by wooorm** [comment]
Hi @dechamps, thanks for your interest in remark!

Correct, remark does not support the non-standard Hugo short-codes by default, however, it’s possible to [extend the parser](https://github.com/wooorm/remark/tree/master/packages/remark-parse#extending-the-parser) in a plugin to take care of that.

But, it seems that those short-codes are a way of templating instead of being part of markdown. You’re gonna have a hard time, I described some of that previously here: https://github.com/wooorm/remark-lint/issues/58.

If you want to work on this, I suggest creating a new repo for the plugin, adding issues on that and pinging me if you need help, or asking questions on [Gitter](https://gitter.im/wooorm/remark)!
