### ISSUE TITLE
HTML comment support / omission?

### ISSUE THREAD

**Issue by probablyup** [wooorm/remark#278]
I received this issue downstream on markdown-to-jsx: https://github.com/probablyup/markdown-to-jsx/issues/110

I think the issue might be that remark treats HTML comments as unprocessed block content, generically labeled with "html". Could the comment be parsed out into its own AST node type or eliminated from the tree?

**Comment by wooorm** [comment]
markdown-to-jsx: JSX doesn’t have comments, right? So what should happen here?

remark: Those comments are part of HTML, so I feel classifying them in remark as html makes a lot of sense? 😛

**Comment by probablyup** [comment]
I feel like this is a weird edge case. The primary issue is if you have
text on the same line as a comment, it gets lumped in with the comment.

If there was a way to split out the text, but keep the comment as HTML that
would be fine.

**Comment by wooorm** [comment]
Ah, I get it! Is this related to something I saw about JSX removing blank lines or something? Normally remark treats it as [three nodes](https://astexplorer.net/#/gist/a5f7f382e606a4f025dee7440714f221/8ae80dbce2a4377e770e97714f85e6966d50e164).

The “root cause” here also resulted in https://github.com/wooorm/strip-markdown/issues/14. But as that conforms to other markdown parsers, I don’t think anything should change here?

**Comment by probablyup** [comment]
Nothing to do with JSX at all actually. This is my reaction to trying to
figure out how to use the AST in this case... I would have expected the
text on the same line to be in its own sibling text node.

**Comment by wooorm** [comment]
Wait, the linked example has three lines, right? No text on the same line?

**Comment by wooorm** [comment]
Sorry for the late response!

This is the way markdown sees HTML: commonmark (and thus markdown-it and GFM) agree. So I’d say this is the way it should be in the syntax tree!
