### ISSUE TITLE
Plugin idea: remark-badges

### ISSUE THREAD

**Issue by niftylettuce** [wooorm/remark#288]
Basically it'd inject badges where you have `<!-- BADGES -->` or something.

And you could configure it in `package.json`, like all the various badges and their links.

**Comment by niftylettuce** [comment]
<https://shields.io/>

**Comment by wooorm** [comment]
Some stuff to note:

Badges are often placed in different places. I personally place them in the main heading normally, or as the next paragraph if the heading is a logo.

Maybe it’s possible to detect which stuff is used? remark has a `.travis.yml`, so it probably wants that badge. There’s also a [codecov script](https://github.com/wooorm/remark/blob/70b6eb5387e29fc89840cb1324580f178d865567/.travis.yml#L5) in `.travis.yml`, so that badge should probably also show up.

Then there’s Gitter. Not sure how to detect that. Maybe you can first find the current badges, and regenerate badges after that again?

**Comment by wooorm** [comment]
See https://github.com/wooorm/remark/issues/291#issuecomment-332175585.
