### ISSUE TITLE
Incorrect parsing as html

### ISSUE THREAD

**Issue by Bouncey** [wooorm/remark#297]
Hi guys, great work you are doing 👍 

We are using you by-proxy through gatsbyjs/gatsby over at freecodecamp/guides. We have run into an issue where markdown inside of code blocks is being incorrectly parsed as html

raw markdown:
 ```
 ```C++
 #include <iostream>
 using namespace std ;
 int main()
 {
     cout<<"Hello World"<<endl;
     return 0;
 }
# with three backticks here
```
[source](https://raw.githubusercontent.com/freeCodeCamp/guides/master/src/pages/cplusplus/introduction-to-cplusplus/index.md)

This is a difference in how it is [parsed on GitHub](https://github.com/freeCodeCamp/guides/blob/master/src/pages/cplusplus/introduction-to-cplusplus/index.md)
```html
<pre>#<span class="pl-k">include</span> <span class="pl-s"><span class="pl-pds">&lt;</span>iostream<span class="pl-pds">&gt;</span></span>
<span class="pl-k">using</span> <span class="pl-k">namespace</span> <span class="pl-en">std</span> <span class="pl-k">;</span>
<span class="pl-k">int</span> <span class="pl-en">main</span>()
{
    cout&lt;&lt;<span class="pl-s"><span class="pl-pds">"</span>Hello World<span class="pl-pds">"</span></span>&lt;&lt;endl;
    <span class="pl-k">return</span> <span class="pl-c1">0</span>;
}</pre>
```
 and how it is [parsed though remark](https://guide.freecodecamp.org/cplusplus/introduction-to-cplusplus/)
```html
<div class="gatsby-highlight">
      <pre class="language-c++"><code>#include <iostream>
using namespace std ;
int main()
{
    cout&lt;&lt;"Hello World"&lt;<endl; return="" 0;="" }<="" code=""></endl;></iostream></code></pre><code>
      </code></div>
```

It seems that `<iostream>` is being incorrectly parsed as html.

**Comment by wooorm** [comment]
Heya! 👋

This is a very big issue. You’re using a lot of tooling: lots of gatsby plugins probably, and in turn lots of remark plugins. Without more info, I have no idea what’s going on here.

You’re posting this issue here on the remark issue tracker, but this project itself is not really related to HTML at all. [Here’s what remark does](https://astexplorer.net/#/gist/07cc51f6e306cabf23334fc26b16a2d8/67b4894a05d82f6565b3be11f58adabd59778ac9) (and that looks fine).

I first suggest checking with `gatsby-transformer-remark` and see what’s going on there. Maybe they have an idea what’s going on. It could be something related to one of the remark plugins, but from this info I wouldn’t know!

Hope this helps! Good luck!

**Comment by Bouncey** [comment]
I just took a look at what `gatsby-transformer-remark` does and 😱 !!!

I'll wade through that lot first, if I need to come back here I will reopen this issue 👍 

Thanks for your time

**Comment by wooorm** [comment]
Sure no problem! Good luck, and let me know if you find something I can help with!
