### ISSUE TITLE
Won't parse correctly when non-breaking space exists

### ISSUE THREAD

**Issue by craftzdog** [wooorm/remark#301]
When rendering Markdown based on user inputs, it may include [non-breaking spaces (charcode: 160)](https://en.wikipedia.org/wiki/Non-breaking_space).
But remark doesn't parse it as spaces, for example:

```
* list
  * item
```

It will be rendered as following:

![screen shot 2017-09-29 at 22 04 25](https://user-images.githubusercontent.com/1332805/31017048-2bafaafc-a562-11e7-8eaa-b32c28cba12e.png)

I got this problem on iOS with remark@7.0.0.

**Comment by wooorm** [comment]
```markdown
* list
  * item
```

I don’t think this is supported in other places, e.g., [markdown-it](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%2A%20list%5Cn%C2%A0%C2%A0%2A%20item%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D), [commonmark](http://spec.commonmark.org/dingus/?text=*%20list%0A%C2%A0%C2%A0*%20item) (link doesn’t work), or here on GH (note the enter here on GH is because Issues have special syntax for newlines):

* list
  * item

...so why should it be supported in remark?

**Comment by craftzdog** [comment]
I understand it should follow the standard.
Just thought it could be solved in the renderer.

**Comment by wooorm** [comment]
Hmm, maybe you can just replace all of them with something like `s = s.replace(/\u00A0/g, ' ')` before passing it to remark?

**Comment by craftzdog** [comment]
Yeah it should work, thanks
