### ISSUE TITLE
Externalise remark(1)

### ISSUE THREAD

**Issue by iamstarkov** [wooorm/remark#98]
it will help to use mdast in the browser because in the browser nobody need cli. what do you think?

**Comment by wooorm** [comment]
Thanks for the Q @iamstarkov.

First, I think the thing you’re trying to do doesn’t match with the motivation. **mdast** is [installable and usable](https://github.com/wooorm/mdast/blob/master/doc/installation.md) in the browser already. Sure, you’ll have to download a view more dependencies when using npm, but not *that* many.

However, I’ve been thinking about this too for a while. The most important reason for breaking the two apart is because they’re pretty different, so separate version control seems useful.

But, the main reason for keeping them together is marketing. I feel it’s much easier to grasp for newcomers when they’re together.

Instead of splitting between API and CLI, I feel for example externalising the parser, the compiler, and several submodules of the CLIs to be much more useful and interesting!

**Comment by iamstarkov** [comment]
sounds like a good plan!

**Comment by wooorm** [comment]
I still like the idea, and I’m going to implement it somewhere in the future, I’ll re-open when I start working on it.
